### ISSUE TITLE
Identification code not found

### ISSUE THREAD

**Issue by wassim** [pirsch-analytics/pirsch-js-sdk#15]
I'm trying to integrate Pirsch to Nextjs 13 but I'm getting an 400 error:

`Identification code not found. Make sure it is correct and you're sending requests for the right domain or subdomain.`

Tested on localhost & production. I can also see my identification code in query params sent to the api.

```js
'use client'

import { useEffect } from 'react'
import { usePathname, useSearchParams } from 'next/navigation'
import { Pirsch } from 'pirsch-sdk/web'

export function Analytics() {
    const id = process.env.NEXT_PUBLIC_PIRSCH_ID as string
    const siteUrl = process.env.NEXT_PUBLIC_SITE_URL as string
    const pathname = usePathname()
    const searchParams = useSearchParams()

    useEffect(() => {
        if (id) {
            const client = new Pirsch({
                identificationCode: id
            })

            const sendHit = async () => {
                let newPageViewPath: string | undefined

                if (pathname) {
                    newPageViewPath = pathname + searchParams.toString()

                    await client
                        .hit({
                            url: siteUrl + newPageViewPath,
                            referrer: document.referrer
                        })
                        .catch(err => console.log(err))
                }
            }

            sendHit()
        }
    }, [pathname, searchParams])

    return <></>
}
```

**Comment by Kugelschieber** [comment]
Hi Wassim,

If the identification code cannot be found, this usually means that you either have it wrong or there is a mismatch between the hostname. The hostname needs to match the one configured on our dashboard (including the subdomain, like www if you use that). You can set the hostname in the constructor, which will replace it for every request.

You can also try resetting the identification code in the settings. Note that we cache it for about 10 minutes, so you have to wait a moment before it is accepted.

Passing the referrer here is not required, this will be done automatically (`document.referrer` is the default).

I haven't been using our SDK for a while now, so maybe @lenovouser sees something I'm missing?

**Comment by lenovouser** [comment]
> I can also see my identification code in query params sent to the api.

Can you show us one example request? Makes it easier to understand any potential issues.

**Comment by Kugelschieber** [comment]
@wassim were you able to resolve the issue?

**Comment by Kugelschieber** [comment]
I'm closing this for now. Feel free to open it again if the issue persists.

**Comment by OD91** [comment]
I have the same issue / get the same error as @wassim with the Client-Side JS SDK. When logging my Identification Code it is definitely the correct one. Can someone help?

This is my code

```typescript
// Import the Pirsch client.
import { Pirsch } from "pirsch-sdk/web"

// Create a client with the identification code you have configured on the Pirsch dashboard.
const client = new Pirsch({
  identificationCode: process.env.NEXT_PUBLIC_PIRSCH_APP_ID as string,
})

// Define the prop types for the sendEventToPirsch function.
interface SendEventToPirschProps {
  eventName: string
  eventProps: { [key: string]: string | number }
  duration?: number
}

// Define the sendEventToPirsch function.
const sendEventToPirsch = async ({
  eventName,
  eventProps,
  duration = undefined,
}: SendEventToPirschProps) => {
  try {
    await client.event(eventName, duration, eventProps)
  } catch (error) {
    console.error("Error sending event to Pirsch:", error)
    console.log("ID CODE", process.env.NEXT_PUBLIC_PIRSCH_APP_ID)
  }
}

export default sendEventToPirsch
