### ISSUE TITLE
Identification code with JS SDK Client-Side not found

### ISSUE THREAD

**Issue by OD91** [pirsch-analytics/pirsch-js-sdk#23]
I'm trying to integrate Pirsch to Nextjs 13 but I'm getting an 400 error:

`PirschApiError: Identification code not found. Make sure it is correct and you're sending requests for the right domain or subdomain.`
, although I log my `Identification code` correctly.

Can someone help or give me a pointer?

My code 👇

```typescript
// Import the Pirsch client.
import { Pirsch } from "pirsch-sdk/web"

// Create a client with the identification code you have configured on the Pirsch dashboard.
const client = new Pirsch({
  identificationCode: process.env.NEXT_PUBLIC_PIRSCH_APP_ID as string,
})

// Define the prop types for the sendEventToPirsch function.
interface SendEventToPirschProps {
  eventName: string
  eventProps: { [key: string]: string | number }
  duration?: number
}

// Define the sendEventToPirsch function.
const sendEventToPirsch = async ({
  eventName,
  eventProps,
  duration = undefined,
}: SendEventToPirschProps) => {
  try {
    await client.event(eventName, duration, eventProps)
  } catch (error) {
    console.error("Error sending event to Pirsch:", error)
    console.log("ID CODE", process.env.NEXT_PUBLIC_PIRSCH_APP_ID)
  }
}

export default sendEventToPirsch

**Comment by OD91** [comment]
ok solved it. what is missing is the `hostname` when you are initiating the new Pirsch client. You should add / call it under the `identificationCode`

![Screenshot 2023-10-03 at 15 26 10](https://github.com/pirsch-analytics/pirsch-js-sdk/assets/43231797/60ad10a0-a2b2-4b85-9b22-ff72eabd2e7f)

**Comment by fxmb** [comment]
Docs are clearly wrong. You need to pass the host url. This took almost a full day to find out....

Could be solved by migrating to TS and requiring these parameters in the type

**Comment by Kugelschieber** [comment]
I'm glad it's working for you now :)

The inline docs are not up-to-date, but the one in the readme is correct. The `hostname` parameter is **not** required. It's only used to rewrite the hostname and for testing purposes. You can check out the web client code here: https://github.com/pirsch-analytics/pirsch-js-sdk/blob/master/src/web.ts#L217

However, the parameter is required to construct the URL for the server-side (Node) integration: https://github.com/pirsch-analytics/pirsch-js-sdk/blob/master/src/client.ts#L61 So, if you use that, you need to set the hostname as required by the configuration type and stated in the readme.

The demo also works without the `hostname` parameter: https://github.com/pirsch-analytics/demo/blob/master/js-sdk-web/src/main.ts We extract the hostname from the URL. It's not part of the request, so you need to make sure that your domain is the same as configured on Pirsch, or rewrite.

**Are you both testing locally by chance?**

> Could be solved by migrating to TS and requiring these parameters in the type

This is a TS repo.
