### ISSUE TITLE
ReferenceError: location is not defined

### ISSUE THREAD

**Issue by peperoli** [pirsch-analytics/pirsch-js-sdk#27]
I am trying to send browser hits to Pirsch with Next.js middleware:

```ts
import { Pirsch } from 'pirsch-sdk/web'

export async function middleware(request: NextRequest) {
  const client = new Pirsch({
    hostname: 'example.com',
    identificationCode: process.env.PIRSCH_CLIENT_ID as string,
  })
  const hit: PirschBrowserHit = {
    url: request.url,
    referrer: request.referrer,
    accept_language: request.headers.get('accept-language') ?? undefined,
  }

  await client.hit(hit).catch(error => {
    console.error(error)
  })

  return NextResponse.next()
}
```
```bash
[ReferenceError: location is not defined]
```

The Web-SDK generates the `url` from `location.href` but there's no `location` global object available.
Can this be changed or should I use a server-side approach instead?

**Comment by Kugelschieber** [comment]
Hi,

`location` is a global object in the browser: https://developer.mozilla.org/en-US/docs/Web/API/Location

Of course, if you render server-side you should use the server-side SDK (https://github.com/pirsch-analytics/pirsch-js-sdk#server-side), as `location` won't be available in that case.

Apparently, you can set "use client" to make it work with Next.js: https://stackoverflow.com/questions/76778589/nextjs-13-build-location-is-not-defined

**Comment by peperoli** [comment]
Thank you for your answer, here's what I tried with the server-side SDK:

```ts
import { Pirsch } from 'pirsch-sdk'

export async function middleware(request: NextRequest) {
  const client = new Pirsch({
    hostname: 'disegnato.ch',
    clientId: process.env.PIRSCH_CLIENT_ID as string,
    clientSecret: process.env.PIRSCH_CLIENT_SECRET as string,
  })
  const hit: PirschHit = {
    url: request.url, 
    ip: request.ip as string,
    user_agent: request.headers.get('user-agent') as string,
    referrer: request.referrer,
    accept_language: request.headers.get('accept-language') ?? undefined,
  }

  await client.hit(hit).catch(error => {
    console.error(error)
  })

  return NextResponse.next()
}
```

```
Module build failed: UnhandledSchemeError: Reading from "node:url" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
Import trace for requested module:
node:url
  ./node_modules/pirsch-sdk/client.js
  ./node_modules/pirsch-sdk/index.js
```

Unfortunately there's no node:url available in Next.js middleware (afaik).

**Comment by Kugelschieber** [comment]
Hmm, can you install it or define Node as the engine?

https://stackoverflow.com/questions/77383943/nextjs-referenceerror-request-is-not-defined-reading-old-version-of-node-s

If that doesn't help, you can also fall back to using the API directly: https://docs.pirsch.io/api-sdks/api-guide It's easy to use if you only send page views and events. Instead of requesting an access token, you can also generate an access key, skipping the whole oAuth flow.

**Comment by peperoli** [comment]
The Node.js runtime is currently not supported in Next.js middleware but possibly in the future: https://github.com/vercel/next.js/discussions/46722.
In my opinion it's worth considering if the `url` could be passed to the SDK directly so it doesn't rely on `node:url`.

Anyway using the API directly works fine for my case, thanks a lot for your help!

**Comment by Kugelschieber** [comment]
Sounds like a good idea! We'll consider it :)
