### ISSUE TITLE
Use PirschSDK in React App

### ISSUE THREAD

**Issue by flaviuhossu** [pirsch-analytics/pirsch-js-sdk#28]
I have a React App that was created with create-react-app. I use the standard Pirsch dashboard integration using that lightweight script in the head in my index.html but I wanted to track some events. I installed the pirsch SDK using `npm i pirsch-sdk`. This is the code I wrote:

`import React, { useEffect } from "react";
import { Pirsch } from "pirsch-sdk/web";

const PirschAPI = () => {
  useEffect(() => {
    const client = new Pirsch({
      identificationCode: "XXXXXfNy73TcKhEB0zE3oIt36sNXXXXX",
    });

    console.log("client: ", client);
    const doEvent = async () => {
      const response = await client.event("test-event", 60, {
        clicks: 1,
        test: "xyz",
      });
      console.log("response: ", response);
      return response;
    };

    doEvent();
  }, []);

  return <div>PirschAPI Component</div>;
};

export default PirschAPI;`

I got the following error: 
`axios_1.default.create is not a function`
The trace:
`TypeError: axios_1.default.create is not a function
    at new PirschWebClient (http://localhost:3000/static/js/bundle.js:25348:39)
    at http://localhost:3000/static/js/bundle.js:5540:20
    at commitHookEffectListMount (http://localhost:3000/static/js/bundle.js:47336:30)
    at invokePassiveEffectMountInDEV (http://localhost:3000/static/js/bundle.js:49025:17)
    at invokeEffectsInDev (http://localhost:3000/static/js/bundle.js:50924:15)
    at commitDoubleInvokeEffectsInDEV (http://localhost:3000/static/js/bundle.js:50907:11)
    at flushPassiveEffectsImpl (http://localhost:3000/static/js/bundle.js:50680:9)
    at flushPassiveEffects (http://localhost:3000/static/js/bundle.js:50618:18)
    at commitRootImpl (http://localhost:3000/static/js/bundle.js:50577:9)
    at commitRoot (http://localhost:3000/static/js/bundle.js:50360:9)`
    
    I checked the node_modules/pirsch-sdk and saw a package.json there with axios as a dependency but axios was not installed inside the pirsch-sdk folder.  I tried to install axios manually in my project but the result is the same.
    What sould I do  ?

**Comment by Kugelschieber** [comment]
Hi Flaviu,

thank you for reporting! :) Searching for `axios_1.default.create is not a function` returns a lot of results where people are having issues with axios, create-react-app, and the bundler. I'm not sure which one it might be related to, but let's try upgrading to the latest version.

I'll release an update for the dependencies. Please try upgrading the SDK to version 2.4.5.

**Comment by flaviuhossu** [comment]
Thank you for your quick response. I updated the library to 2.4.5 but the issue still persists.

**Comment by Kugelschieber** [comment]
Hmm, weird. @lenovouser will take a look in a few days :)

For now, you could try using the script snippet and call the global `pirsch` event function. That should be available from react.

**Comment by flaviuhossu** [comment]
Thanks. That's what I've done.

**Comment by Kugelschieber** [comment]
Awesome! Still kind of weird that it cannot find axios... We'll look into it :)
