### ISSUE TITLE
Type definitions for the JS snippet client

### ISSUE THREAD

**Issue by elsbrock** [pirsch-analytics/pirsch-js-sdk#29]
Hi! I'm building a project where I'm using the default JS snippet (so far) but I have instrumented parts of the code. I was hoping I could use the type definitions from this SDK, but looks like it's more low-level (as written in the query) - ie. you need to instantiate it yourself etc..

For now I don't wanna do that, but would it be possible to include the type of the snippet-client in here too? At the moment I'm using `any`: https://github.com/elsbrock/hetzner-radar/blob/b77ad1938d69175617a89e304c1b394d2f6cfdd7/src/routes/analyze/%2Bpage.svelte#L2

**Comment by Kugelschieber** [comment]
Hi,

Wouldn't it be a bit overkill to pull in the entire SDK just for the `pirsch` event function definition? You could create a file containing the definition and import it from there. Like this:

```
declare function pirsch(event_name: string, metadata?: {[key: string]: string | number}): void;

// Example calls
pirsch("foo");
pirsch("bar", {
    key0: "value",
    key1: 42
});
```

**Comment by elsbrock** [comment]
Sure, if it's that simple I'm happy to use this – wasn't sure if there's more to it.

FWIW, I'm using a bundler, so I was assuming (or more: hoping) that it'd anyhow throw away all unused code 🙁
