### ISSUE TITLE
Domain API responses status 200 when bearer token is missing

### ISSUE THREAD

**Issue by rogervanwile** [pirsch-analytics/pirsch-js-sdk#4]
I just came across a bug that affects at least the JS SDK.

When I call the domain API without a bearer token, it returns a status `200` and data `null`.

```
curl --location --request GET 'https://api.pirsch.io/api/v1/domain' \
--header 'Content-Type: application/json' \
--data-raw '{
    "client_id": "[client_id]",
    "client_secret": "[client_secret]"
}'
```

So the JS SDK doesn't work, because it tries to call the API when creating the client without login and then checks the status in the `catch`.

https://github.com/pirsch-analytics/pirsch-js-sdk/blob/master/Client.ts#L299

**Comment by Kugelschieber** [comment]
Fixed.
